# Generated by Django 4.0.3 on 2022-06-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='clienteid',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='parqueid',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='periodicidadeid',
        ),
        migrations.RemoveField(
            model_name='dia',
            name='periodicidadeid',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='clienteid',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='pagamentoid',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='contratoid',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='registoid',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='reservaid',
        ),
        migrations.RemoveField(
            model_name='reclamacao',
            name='faturaid',
        ),
        migrations.RemoveField(
            model_name='registomovimento',
            name='parqueid',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='parqueid',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='viaturaid',
        ),
        migrations.DeleteModel(
            name='TabelaMatriculas',
        ),
        migrations.RemoveField(
            model_name='tabelaprecos',
            name='parqueid',
        ),
        migrations.RemoveField(
            model_name='tabelaprecos',
            name='reservaid',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='contratoid',
        ),
        migrations.RemoveField(
            model_name='viatura',
            name='registo_movimentoid',
        ),
    ]
